### PR TITLE
Remove contributing to-do for custom route

### PR DESCRIPTION
**Pull request by JulianLeviston**
Remove contributing to-do for custom route

### CODE REVIEW

**Comment by martinklepsch** [comment]
@JulianLeviston Thanks!

**Comment by JulianLeviston** [comment]
So it's not right? I mean you won't merge it?

**Comment by martinklepsch** [comment]
I merged it: https://github.com/martinklepsch/s3-beam/commit/981cfd626e184260f072f436663c8b181b139182 :)

**Comment by JulianLeviston** [comment]
Oh weird. Sorry, I didn't understand the "closed with unmerged commits" thing, really. :) All good. Thanks :)

**Comment by martinklepsch** [comment]
No worries :smiley:

**Pull request closed without merging**
